# Pull official base image as base to use in later stage
FROM node:alpine AS base

# Workdir
WORKDIR /app

# install app dependencies
COPY package.json package.json
COPY package-lock.json package-lock.json
COPY . .
RUN npm install && npm run build
CMD ["npm", "run", "test-main"]
